version: '3'

services:
  api-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-news
    ports:
      - 3000:3000
    volumes:
      - C:\\development\\NextJS\\next-short-news\\public:/opt/app/public
    restart: always
    networks:
      - home
networks:
  home:
    driver: bridge
